*** Settings ***

Resource    createAccountPage.resource
Resource    deleteSomeAccountInfo.resource
Resource    deliveryForm.resource
Resource    headerMenu.resource
Resource    loginForm.resource
Resource    loginPage.resource
Resource    myDashboardPage.resource
Resource    newsletterForm.resource
Resource    orderSummaryPage.resource
Resource    popupElement.resource
Resource    searchResultPage.resource
Resource    shoppingBasketPage.resource
Resource    updateAccountPage.resource



