deliveryForm_salutation_option = "xpath=//*[@id='dwfrm_checkout_shipping_address_title-Mrs']"
deliveryForm_firstname_input = "xpath=//*[@name='dwfrm_checkout_shipping_address_firstName']"
deliveryForm_lastname_input = "xpath=//*[@name='dwfrm_checkout_shipping_address_lastName']"
deliveryForm_adress_input = "xpath=//*[@name='dwfrm_checkout_shipping_address_address1']"
deliveryForm_postalCode_input = "xpath=//*[@name='dwfrm_checkout_shipping_address_postalCode']"
deliveryForm_city_input = "xpath=//*[@name='dwfrm_checkout_shipping_address_city']"
deliveryForm_email_input = "xpath=//*[@name='dwfrm_checkout_shipping_address_email']"
deliveryForm_phoneNumber_input = "xpath=//*[@name='dwfrm_checkout_shipping_address_phone']"
deliveryForm_newsletter_option="xpath=//input[@id='dwfrm_checkout_shipping_communicationpreference_newsletterSubscription-no']"
deliveryForm_login_as_guest_user_link = "xpath=//*[@class='i-link full-width continue-as-guest text-center display-inline-block mb-20']/a"
deliveryForm_save_button = "xpath=//*[@name='dwfrm_checkout_shipping_save']"
#are
deliveryForm_are_district_input="xpath=//input[@name='dwfrm_checkout_shipping_address_district']"
deliveryForm_are_city_select="xpath=//i-select[@class='i-dropdown floating-label flex-form-item flex-form-item__half display-inline-block']"
deliveryForm_are_city_input="xpath=//input[@class='choices__input choices__input--cloned']"
deliveryForm_are_city_choice="xpath=//div[@id='dwfrm_checkout_shipping_address_citySelect_city_$CITYVALUE$']"
#ROU
deliveryForm_rou_county_select = "xpath=//i-select[@data-auto-id='province']"
deliveryForm_rou_county_choice_cluj = "xpath=//div[@class='choices__list']/div[@data-value='Cluj']"
#MYS
deliveryForm_state_select = "xpath=//i-select[@class='i-dropdown floating-label flex-form-item flex-form-item__half display-inline-block']"
deliveryForm_state_choice = "xpath=//div[@class='choices__item choices__item--choice choices__item--selectable' and @data-id='2']"


deliveryForm_payment_credit_card_button= "xpath=//*[@id='dwfrm_checkout_billing_payment_selectedPaymentMethodID-CREDIT_CARD']"
deliveryForm_payment_card_number_input= "xpath=//*[@name='dwfrm_checkout_billing_payment_creditcard_number']"
deliveryForm_payment_name_on_card_input= "xpath=//*[@name='dwfrm_checkout_billing_payment_creditcard_owner']"
deliveryForm_payment_card_expiration_date_input= "xpath=//*[@name='dwfrm_checkout_billing_payment_creditcard_creditCardExpirationDate']"
deliveryForm_payment_cvn_input= "xpath=//*[@name='dwfrm_checkout_billing_payment_creditcard_cvn']"
deliveryForm_payment_accept_general_terms_and_conditions_button= "xpath=//i-payment-consent-block[@class='i-payment-consent-block full-width hide-mobile grid']//*[starts-with(@id, 'termsandconditions')]"
deliveryForm_payment_pay_button= "xpath=//i-billing//*[@name='dwfrm_checkout_billing_paymentconsent_save']"
deliveryForm_payment_thanks_for_order_title ="xpath=//h1[@class='confirmation__heading mt-10 mb-20']"