headerMenu_login_button = "xpath=//*[@class='header-menu-login__icon header-menu__icon flex-vertical-center']"
headerMenu_search_bar_button = "xpath=//*[@id='q']"
headerMenu_search_button = "xpath=//*[@class='submit-search flex-align-center cba-button-style']"
headerMenu_minibag_button="xpath=//*[@class='minibag-tooltip display-inline-block align-middle pb-s']"
headerMenu_plus_button="xpath=//*[@class='product-info full-width']//*[@data-action='increase']"
headerMenu_myAccount_popup_menu="xpath= //div[@class='tippy-content']"
headerMenu_my_points_recap_button = "xpath=//div[@class='tippy-content']//a[@title='My points recap']"
headerMenu_my_rewards_button = "xpath=//div[@class='tippy-content']//a[@title='My rewards']"
