updateAccountPage_salutation_option ="xpath=//*[@id='dwfrm_cba__profile_customer_title-$SALUTATION$']"
updateAccountPage_first_name_input="xpath=//*[starts-with(@id, 'firstname')]"
updateAccountPage_last_name_input="xpath=//*[starts-with(@id, 'lastname')]"
updateAccountPage_birthday_input="xpath=//*[starts-with(@id, 'birthday')]"
updateAccountPage_birthday_date_invalid_message = "xpath=//*[starts-with(@id, 'error_birthday')]"
updateAccountPage_phone_number_country_code_select = "xpath=//select[starts-with(@id,'phoneCountryCode')]/parent::div"
updateAccountPage_phone_number_country_code_option = "xpath=//*[@id='dwfrm_cba__profile_customer_phoneCountryCode_$COUNTRY_ALPHA2$']"
updateAccountPage_phone_number_input = "xpath=//div[contains(@class,'i-phone-input__info')]/input"
updateAccountPage_email_optin_option="xpath=//*[@id='dwfrm_cba__profile_customer_emailoptin-$EMAIL_OPTIN_VALUE$']"
updateAccountPage_sms_optin_option="xpath=//*[@id='dwfrm_cba__profile_customer_smsoptin-yes']"
updateAccountPage_is_loyalty_member_option="xpath=//*[@id='dwfrm_cba__profile_customer_issalesforceloyaltymember-$IS_LOYALTY_MEMBER_VALUE$']"
updateAccountPage_submit_button = "xpath=//*[starts-with(@id, 'submit')]"
