from contactPage.contactPage import *
from contactPage.contactTab import *
from contactPage.historyTab import *
from contactPage.sourceTraceabilityTab import *
from contactPage.trackingTab import *
from leftMenu.contactsTab import *
from leftMenu.globalSearchTab import *
from leftMenu.leftMenu import *
from leftMenu.listOfValuesTab import *
from leftMenu.tasksTab import *
from homePage import *
from loginPage import *