*** Settings ***

Resource    contactInformation_generators.resource
Resource    generate_testData_createAccount.resource
Resource    generate_testData_lastInteractionDate.resource
Resource    generate_testData_subscribeNewsletter.resource
Resource    gererate_testData_transaction.resource
Resource    generate_testData_updateAccount.resource
Resource    generate_testData_connect.resource
Resource    update_dictionary.resource
